In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns',None)
# pd.set_option('display.width',None)

In [2]:
#Reading Data
df = pd.read_excel("training_data.xlsx")
df

,ID,Severity,Ventilation,Mean Age,% Male,Any Comorbidity,Hypertension,Diabetes,Cardiovascular Disease (incl. CAD),Chronic obstructive lung (COPD),...,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90
0,1,All,Both,NaN,0.6230,0.4760,0.3000,0.1900,0.0800,0.0300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Severe/Critical Only,Both,NaN,0.7037,0.6667,0.4815,0.3148,0.2407,0.0741,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,All,Both,NaN,0.5912,0.4015,0.2336,0.1387,0.0146,0.0146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,All,Both,NaN,0.6030,NaN,NaN,0.1160,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,All,Both,NaN,0.6160,NaN,NaN,0.1010,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,Severe/Critical Only,NaN,NaN,0.6630,NaN,0.3880,0.1220,0.0920,NaN,...,27.3,41.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.68
471,198,NaN,Both,NaN,0.6600,NaN,0.6300,0.3600,0.1900,0.0900,...,39.0,61.0,0.89,0.81,NaN,0.30,NaN,NaN,NaN,0.33
472,199,Severe/Critical Only,Both,65.0,0.5900,0.7100,0.4336,0.2368,0.0702,NaN,...,26.0,32.0,NaN,NaN,0.06,0.01,0.05,NaN,25.0,0.14
473,199,Severe/Critical Only,Both,66.0,0.5600,0.7100,0.4600,0.2500,0.0900,NaN,...,26.0,31.0,NaN,NaN,0.05,0.01,0.03,NaN,25.0,0.15
474,199,Severe/Critical Only,Both,64.0,0.6500,0.7100,0.3800,0.2100,0.0300,NaN,...,26.0,33.0,NaN,NaN,0.09,0.00,0.09,NaN,24.0,0.13

In [3]:
#Checking DataTypes
df.dtypes

ID               int64
Severity        object
Ventilation     object
Mean Age       float64
% Male         float64
                ...
Unnamed: 86    float64
Unnamed: 87    float64
Unnamed: 88    float64
Unnamed: 89    float64
Unnamed: 90    float64
Length: 91, dtype: object

In [4]:
df["Mortality"].mode()

0    0
dtype: object

In [5]:
df["Mortality"].replace(["0%%","na"],'0',inplace = True)

In [6]:
df["Mortality"][407]

'0'

In [7]:
df["Mortality"]  = df["Mortality"].astype("float64")

In [8]:
len(df)

475

In [9]:
(df.isna().sum()/len(df))*100

ID              0.000000
Severity        3.578947
Ventilation    36.631579
Mean Age       46.947368
% Male          9.473684
                 ...
Unnamed: 86    97.263158
Unnamed: 87    97.684211
Unnamed: 88    98.315789
Unnamed: 89    96.842105
Unnamed: 90    92.421053
Length: 91, dtype: float64

In [10]:
df = df[df.columns[0:-36]]
df

,ID,Severity,Ventilation,Mean Age,% Male,Any Comorbidity,Hypertension,Diabetes,Cardiovascular Disease (incl. CAD),Chronic obstructive lung (COPD),...,Alanine Aminotransferase (U/L),Aspartate Aminotransferase (U/L),Antibiotic,Antiviral (Any),Heart failure,Acute kidney injury (AKI),Secondary infection/ Bacterial infection,"ICU length of stay, days","Hospital length of stay, days",Mortality
0,1,All,Both,NaN,0.6230,0.4760,0.3000,0.1900,0.0800,0.0300,...,30.0,NaN,0.9476,0.2147,0.2304,0.1466,0.1466,8,11,0.28
1,1,Severe/Critical Only,Both,NaN,0.7037,0.6667,0.4815,0.3148,0.2407,0.0741,...,40.0,NaN,0.9815,0.2222,0.5185,0.5000,0.5000,8,7.5,1.00
2,1,All,Both,NaN,0.5912,0.4015,0.2336,0.1387,0.0146,0.0146,...,27.0,NaN,0.9343,0.2117,0.1168,0.0073,0.0073,7,12,0.00
3,2,All,Both,NaN,0.6030,NaN,NaN,0.1160,NaN,NaN,...,33.0,34.0,0.9500,0.4700,0.0051,0.0468,0.0365,10,15,0.16
4,2,All,Both,NaN,0.6160,NaN,NaN,0.1010,NaN,NaN,...,33.0,33.0,0.9490,0.9490,0.0000,0.0320,0.0110,6,14,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,Severe/Critical Only,NaN,NaN,0.6630,NaN,0.3880,0.1220,0.0920,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.56
471,198,NaN,Both,NaN,0.6600,NaN,0.6300,0.3600,0.1900,0.0900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.58
472,199,Severe/Critical Only,Both,65.0,0.5900,0.7100,0.4336,0.2368,0.0702,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00
473,199,Severe/Critical Only,Both,66.0,0.5600,0.7100,0.4600,0.2500,0.0900,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
474,199,Severe/Critical Only,Both,64.0,0.6500,0.7100,0.3800,0.2100,0.0300,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [11]:
df = df[pd.DataFrame(df.isna().sum() ).sort_values(by = 0)[0:22].index]

In [12]:
df.columns

Index(['ID', 'Mortality', 'Severity', '% Male', 'Fever (temperature ≥37·3°C)',
       'Cough', 'Diabetes', 'Hypertension', 'Ventilation',
       'Cardiovascular Disease (incl. CAD)',
       'Lymphocyte Count (10^9/L) - Median',
       'White Blood Cell Count (10^9/L) - Median',
       'Chronic obstructive lung (COPD)', 'Diarrhoea',
       'White Blood Cell Count (10^9/L) - LQ', 'Mean Age',
       'White Blood Cell Count (10^9/L) - UQ', 'Chronic kidney/renal disease',
       'Shortness of Breath (dyspnoea)', 'Lymphocyte Count (10^9/L) - UQ',
       'Lymphocyte Count (10^9/L) - LQ', 'Cancer (Any)'],
      dtype='object')

In [13]:
df["Severity"].fillna(df["Severity"].mode()[0],inplace = True)
df["% Male"].fillna(df["% Male"].median(),inplace = True)

C:\Users\aakas\Anaconda\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [14]:
df.isna().sum()

ID                                            0
Mortality                                     0
Severity                                      0
% Male                                        0
Fever (temperature ≥37·3°C)                 119
Cough                                       135
Diabetes                                    150
Hypertension                                166
Ventilation                                 174
Cardiovascular Disease (incl. CAD)          180
Lymphocyte Count (10^9/L) - Median          186
White Blood Cell Count (10^9/L) - Median    191
Chronic obstructive lung (COPD)             213
Diarrhoea                                   215
White Blood Cell Count (10^9/L) - LQ        222
Mean Age                                    223
White Blood Cell Count (10^9/L) - UQ        224
Chronic kidney/renal disease                225
Shortness of Breath (dyspnoea)              232
Lymphocyte Count (10^9/L) - UQ              238
Lymphocyte Count (10^9/L) - LQ              238
Cancer (Any)                                242
dtype: int64

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
lr = LinearRegression()
le = LabelEncoder()
scaler = MinMaxScaler(feature_range=(0,1))

In [16]:
NC = ['Fever (temperature ≥37·3°C)',
       'Cough', 'Diabetes', 'Hypertension',
       'Cardiovascular Disease (incl. CAD)',
       'Lymphocyte Count (10^9/L) - Median',
       'White Blood Cell Count (10^9/L) - Median',
       'Chronic obstructive lung (COPD)', 'Diarrhoea',
       'White Blood Cell Count (10^9/L) - LQ', 'Mean Age',
       'White Blood Cell Count (10^9/L) - UQ', 'Chronic kidney/renal disease',
       'Shortness of Breath (dyspnoea)', 'Lymphocyte Count (10^9/L) - UQ',
       'Lymphocyte Count (10^9/L) - LQ', 'Cancer (Any)']

In [17]:
df["Severity_label"]= pd.DataFrame(le.fit_transform(df["Severity"]))
df["Severity_scaler"] = scaler.fit_transform(df[["Severity_label"]])

C:\Users\aakas\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\aakas\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
df = df.reindex(columns = ['ID', 'Mortality', 'Severity','Severity_label',
       'Severity_scaler', '% Male', 'Fever (temperature ≥37·3°C)',
       'Cough', 'Diabetes', 'Hypertension',
       'Cardiovascular Disease (incl. CAD)',
       'Lymphocyte Count (10^9/L) - Median',
       'White Blood Cell Count (10^9/L) - Median',
       'Chronic obstructive lung (COPD)', 'Diarrhoea',
       'White Blood Cell Count (10^9/L) - LQ', 'Mean Age',
       'White Blood Cell Count (10^9/L) - UQ', 'Chronic kidney/renal disease',
       'Shortness of Breath (dyspnoea)', 'Lymphocyte Count (10^9/L) - UQ',
       'Lymphocyte Count (10^9/L) - LQ', 'Cancer (Any)'])

In [19]:
df1 = df.copy()
df1 = df1.drop(["Severity","Severity_label"],axis=1)

In [20]:
df1

,ID,Mortality,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Cough,Diabetes,Hypertension,Cardiovascular Disease (incl. CAD),Lymphocyte Count (10^9/L) - Median,...,Chronic obstructive lung (COPD),Diarrhoea,White Blood Cell Count (10^9/L) - LQ,Mean Age,White Blood Cell Count (10^9/L) - UQ,Chronic kidney/renal disease,Shortness of Breath (dyspnoea),Lymphocyte Count (10^9/L) - UQ,Lymphocyte Count (10^9/L) - LQ,Cancer (Any)
0,1,0.28,0.000000,0.6230,0.9400,0.7900,0.1900,0.3000,0.0800,1.00,...,0.0300,0.0471,4.5,NaN,9.50,0.0168,NaN,1.3,0.6,0.0168
1,1,1.00,0.857143,0.7037,0.9444,0.7222,0.3148,0.4815,0.2407,0.60,...,0.0741,0.0370,6.9,NaN,13.90,0.0370,NaN,0.8,0.5,0.0000
2,1,0.00,0.000000,0.5912,0.9416,0.8175,0.1387,0.2336,0.0146,1.10,...,0.0146,0.0511,4.3,NaN,7.70,0.0000,NaN,1.5,0.8,0.0700
3,2,0.16,0.000000,0.6030,0.9150,NaN,0.1160,NaN,NaN,0.90,...,NaN,0.0206,5.1,NaN,9.40,NaN,NaN,1.2,0.6,0.0300
4,2,0.15,0.000000,0.6160,0.8990,NaN,0.1010,NaN,NaN,0.80,...,NaN,0.0420,5.3,NaN,9.60,NaN,NaN,1.4,0.6,0.0510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,0.56,0.857143,0.6630,0.8570,0.7040,0.1220,0.3880,0.0920,0.58,...,NaN,0.0510,5.1,NaN,11.96,NaN,NaN,NaN,NaN,0.0410
471,198,0.58,0.000000,0.6600,0.7100,0.6600,0.3600,0.6300,0.1900,0.80,...,0.0900,0.1200,NaN,NaN,NaN,0.1400,0.74,NaN,NaN,0.0700
472,199,1.00,0.857143,0.5900,0.3665,NaN,0.2368,0.4336,0.0702,0.80,...,NaN,0.0300,4.4,65.0,8.30,0.0000,NaN,NaN,NaN,NaN
473,199,0.00,0.857143,0.5600,0.3500,NaN,0.2500,0.4600,0.0900,0.80,...,NaN,0.0300,4.4,66.0,8.30,0.0000,NaN,NaN,NaN,NaN
474,199,0.00,0.857143,0.6500,0.4000,NaN,0.2100,0.3800,0.0300,0.70,...,NaN,0.0300,4.5,64.0,8.30,0.0000,NaN,NaN,NaN,NaN

In [21]:
df1[df1[NC[1]].notnull()].iloc[:,[0,1,2,3,5]][[NC[1]]]

      Cough
0    0.7900
1    0.7222
2    0.8175
6    0.5900
7    0.0000
..      ...
463  0.7890
468  0.6910
469  0.6800
470  0.7040
471  0.6600

[340 rows x 1 columns]

In [22]:
df1[df1[NC[1]].notnull()].iloc[:,[0,1,2,3,5]].iloc[:,0:4]

      ID  Mortality  Severity_scaler  % Male
0      1       0.28         0.000000  0.6230
1      1       1.00         0.857143  0.7037
2      1       0.00         0.000000  0.5912
6      3       0.04         0.000000  0.5200
7      3       0.00         0.000000  0.2700
..   ...        ...              ...     ...
463  193       0.36         0.857143  0.7370
468  197       0.36         0.000000  0.5650
469  197       0.39         0.571429  0.4880
470  197       0.56         0.857143  0.6630
471  198       0.58         0.000000  0.6600

[340 rows x 4 columns]

In [23]:
lr.fit(df1[df1[NC[3]].notnull()].iloc[:,[0,1,2,3,4+3]].iloc[:,0:4],
       df1[df1[NC[3]].notnull()].iloc[:,[0,1,2,3,4+3]][[NC[3]]])

LinearRegression()

In [24]:
lr.predict(df1[df1[NC[0]].isnull()].iloc[:,[0,1,2,3,4]].iloc[:,0:4])

array([[0.49330372],
       [0.46201425],
       [0.54623361],
       [0.18530677],
       [0.18332432],
       [0.17125289],
       [0.16250267],
       [0.18759891],
       [0.17751645],
       [0.20487135],
       [0.62004668],
       [0.21675517],
       [0.26948205],
       [0.28558531],
       [0.250735  ],
       [0.33835019],
       [0.21184053],
       [0.17262856],
       [0.17115624],
       [0.2790667 ],
       [0.27174653],
       [0.2835662 ],
       [0.19257024],
       [0.59785946],
       [0.1931807 ],
       [0.18755014],
       [0.19197867],
       [0.19396112],
       [0.16535149],
       [0.60265066],
       [0.57789038],
       [0.51096707],
       [0.67827534],
       [0.51096707],
       [0.51096707],
       [0.51096707],
       [0.67827534],
       [0.67827534],
       [0.51096707],
       [0.67827534],
       [0.67827534],
       [0.51096707],
       [0.51096707],
       [0.67827534],
       [0.51096707],
       [0.67827534],
       [0.51096707],
       [0.51096707],
       [0.51096707],
       [0.67827534],
       [0.67827534],
       [0.51096707],
       [0.51096707],
       [0.51096707],
       [0.51096707],
       [0.67827534],
       [0.23653311],
       [0.18704917],
       [0.64106646],
       [0.26694087],
       [0.20767342],
       [0.63658656],
       [0.17826461],
       [0.1780973 ],
       [0.17859923],
       [0.24359467],
       [0.29427457],
       [0.1435935 ],
       [0.24286496],
       [0.19450453],
       [0.38499046],
       [0.41336071],
       [0.59979375],
       [0.22438788],
       [0.33106344],
       [0.45499776],
       [0.17609585],
       [0.25022028],
       [0.2793715 ],
       [0.21175597],
       [0.45726899],
       [0.19101888],
       [0.18423856],
       [0.2456731 ],
       [0.47606854],
       [0.26042871],
       [0.23770945],
       [0.21754645],
       [0.22323493],
       [0.22853773],
       [0.21273501],
       [0.27538405],
       [0.20405966],
       [0.10869394],
       [0.35736382],
       [0.24027704],
       [0.27533962],
       [0.29824352],
       [0.31445508],
       [0.36784941],
       [0.41410431],
       [0.47612367],
       [0.68739332],
       [0.2233878 ],
       [0.1802272 ],
       [0.27553658],
       [0.21156434],
       [0.4131092 ],
       [0.20609519],
       [0.20755004],
       [0.21052371],
       [0.21349739],
       [0.43216806],
       [0.17845411],
       [0.31572216],
       [0.22339545],
       [0.21967717],
       [0.20073385],
       [0.21468341]])

In [25]:
new_values = []
for i in range(len(NC)):
    lr.fit(df1[df1[NC[i]].notnull()].iloc[:,[0,1,2,3,4+i]].iloc[:,0:4],df1[df1[NC[i]].notnull()].iloc[:,[0,1,2,3,4+i]][[NC[i]]])
    new_values.append(lr.predict(df1[df1[NC[i]].isnull()].iloc[:,[0,1,2,3,4]].iloc[:,0:4]))

In [26]:
notnull = []
isnull = []
for  i in range(len(NC)):
    notnull.append(df1[df1[NC[i]].notnull()].iloc[:,[0,1,2,3,4+i]])
    isnull.append(df1[df1[NC[i]].isnull()].iloc[:,[0,1,2,3,4+i]])
    notnull[i].reset_index(drop=True,inplace = True)
    isnull[i].reset_index(drop=True,inplace = True)    
    isnull[i][NC[i]]  = pd.DataFrame(new_values[i])[0] 
    df1.iloc[:,4+i] = pd.concat([notnull[i],isnull[i]],ignore_index=True).iloc[:,-1]

In [54]:
df1

,ID,Mortality,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Cough,Diabetes,Hypertension,Cardiovascular Disease (incl. CAD),Lymphocyte Count (10^9/L) - Median,...,Chronic obstructive lung (COPD),Diarrhoea,White Blood Cell Count (10^9/L) - LQ,Mean Age,White Blood Cell Count (10^9/L) - UQ,Chronic kidney/renal disease,Shortness of Breath (dyspnoea),Lymphocyte Count (10^9/L) - UQ,Lymphocyte Count (10^9/L) - LQ,Cancer (Any)
0,1,0.28,0.000000,0.6230,0.940000,0.790000,0.190000,0.300000,0.080000,1.000000,...,0.030000,0.047100,4.500000,49.500000,9.500000,0.016800,0.420000,1.300000,0.600000,0.016800
1,1,1.00,0.857143,0.7037,0.944400,0.722200,0.314800,0.481500,0.240700,0.600000,...,0.074100,0.037000,6.900000,44.900000,13.900000,0.037000,0.000000,0.800000,0.500000,0.000000
2,1,0.00,0.000000,0.5912,0.941600,0.817500,0.138700,0.233600,0.014600,1.100000,...,0.014600,0.051100,4.300000,48.800000,7.700000,0.000000,0.430000,1.500000,0.800000,0.070000
3,2,0.16,0.000000,0.6030,0.915000,0.590000,0.116000,0.150000,0.100000,0.900000,...,0.110000,0.020600,5.100000,52.300000,9.400000,0.040000,0.430000,1.200000,0.600000,0.030000
4,2,0.15,0.000000,0.6160,0.899000,0.000000,0.101000,0.130000,0.200000,0.800000,...,0.070000,0.042000,5.300000,49.500000,9.600000,0.000000,0.800000,1.400000,0.600000,0.051000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,0.56,0.857143,0.6630,0.601472,0.663329,0.259824,0.268238,0.349657,3.025559,...,0.078594,0.200831,4.911807,49.490090,5.340416,0.020814,0.385844,3.434263,2.926642,0.084291
471,198,0.58,0.000000,0.6600,0.637644,0.623641,0.305341,0.336715,0.148943,3.090282,...,0.091873,0.249024,4.893536,50.128415,5.308829,0.016272,0.529499,2.904315,2.419905,0.084849
472,199,1.00,0.857143,0.5900,0.636763,0.657676,0.171766,0.490725,0.124150,3.109430,...,0.124468,0.250866,4.811602,55.758071,5.063910,0.101207,0.601620,2.178207,1.857964,0.180093
473,199,0.00,0.857143,0.5600,0.624952,0.672993,0.245874,0.432168,0.271933,2.914092,...,0.041530,0.234978,4.919154,61.961463,6.392853,0.064457,0.384576,4.444120,3.741072,0.075274
474,199,0.00,0.857143,0.6500,0.569376,0.680539,0.134597,0.178454,0.097850,2.814607,...,0.045788,0.239986,6.126312,55.020322,8.667605,0.066649,0.409184,4.745771,4.023642,0.065910

In [55]:
test = pd.read_excel("test_data.xlsx")

In [56]:
test

,ID,Severity,Ventilation,Mean Age,% Male,Any Comorbidity,Hypertension,Diabetes,Cardiovascular Disease (incl. CAD),Chronic obstructive lung (COPD),...,Albumin (g/L),Alanine Aminotransferase (U/L),Aspartate Aminotransferase (U/L),Antibiotic,Antiviral (Any),Heart failure,Acute kidney injury (AKI),Secondary infection/ Bacterial infection,"ICU length of stay, days","Hospital length of stay, days"
0,155,Mild only,Both,48.900000,0.3410,0.3250,0.1510,0.1190,0.0630,NaN,...,NaN,23.00,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,156,Severe/Critical Only,Both,NaN,0.7500,0.6800,0.2500,0.1700,0.1100,0.1100,...,NaN,37.00,36.0,NaN,1.000,NaN,0.060,NaN,10.0,16.0
2,156,Severe/Critical Only,Ventilation only,NaN,0.7900,0.7400,0.2600,0.2400,0.1800,0.1500,...,NaN,48.00,39.0,NaN,1.000,NaN,0.050,NaN,12.0,17.0
3,156,Severe/Critical Only,Non-ventilation only,NaN,0.6800,0.5800,0.2100,0.0500,0.0000,0.0500,...,NaN,27.00,35.0,NaN,1.000,NaN,0.060,NaN,0.0,13.0
4,157,All,Both,52.943333,0.4654,NaN,0.2121,0.0938,0.0733,0.0327,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,157,All,Both,44.740000,0.2927,NaN,0.1341,0.0610,0.0610,0.0244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,157,All,Both,52.680000,0.4938,NaN,0.1728,0.0741,0.0370,0.0494,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,157,All,Both,61.410000,0.6098,NaN,0.3293,0.1463,0.1220,0.0244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,158,All,Both,36.020000,0.5198,NaN,NaN,NaN,NaN,NaN,...,NaN,19.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,158,All,Both,40.500000,0.5880,NaN,NaN,NaN,NaN,NaN,...,NaN,20.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.5
10,158,All,Both,26.500000,0.3750,NaN,NaN,NaN,NaN,NaN,...,NaN,15.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.5
11,159,All,NaN,49.000000,0.4700,NaN,0.1900,0.1000,0.0600,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,159,Mild only,NaN,45.000000,0.4400,NaN,0.1000,0.0700,0.0300,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,159,Severe/Critical Only,NaN,67.500000,0.6000,NaN,0.6500,0.2500,0.2000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,160,All,Both,38.760000,0.5680,0.2720,NaN,NaN,0.1440,0.0160,...,NaN,24.00,27.0,0.632,1.000,NaN,NaN,0.568,NaN,14.8
15,160,Severe/Critical Only,Both,49.400000,0.6400,NaN,NaN,NaN,NaN,NaN,...,NaN,25.00,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,160,Mild Only,Both,39.470000,0.5500,NaN,NaN,NaN,NaN,NaN,...,NaN,24.00,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,160,Severe/Critical Only,Ventilation only,69.000000,1.0000,NaN,NaN,NaN,1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,160,Severe/Critical Only,Ventilation only,40.000000,1.0000,NaN,NaN,NaN,0.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,160,Severe/Critical Only,Ventilation only,21.000000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,NaN,NaN,NaN,1.000,1.000,NaN,NaN,NaN,10.0,NaN
20,160,Severe/Critical Only,Ventilation only,67.000000,1.0000,NaN,NaN,NaN,1.0000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,161,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,161,Both,NaN,44.000000,0.6200,0.4900,0.3400,0.1700,0.0800,0.0700,...,NaN,23.00,30.0,0.910,0.860,0.240,0.110,NaN,NaN,NaN
23,161,Both,NaN,62.000000,0.7300,0.6300,0.4800,0.2100,0.1400,0.1000,...,NaN,28.00,45.0,0.930,0.790,0.490,0.250,NaN,NaN,NaN
24,161,Both,NaN,37.000000,0.5500,0.3900,0.2400,0.1400,0.0400,0.0400,...,NaN,20.00,25.0,0.890,0.910,0.030,0.010,NaN,NaN,NaN
25,162,All,Both,45.300000,0.4740,NaN,0.1650,0.0630,0.0420,0.0530,...,NaN,NaN,NaN,0.726,0.937,NaN,NaN,NaN,NaN,NaN
26,162,All,Both,48.000000,0.4660,NaN,0.1720,0.0520,0.0520,0.0170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,162,All,Both,41.100000,0.4860,NaN,0.1620,0.0810,0.0270,0.1080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,169,All,Both,45.000000,0.4900,0.5270,0.3090,0.1640,0.0360,NaN,...,NaN,21.00,24.0,0.527,1.000,NaN,0.055,0.073,NaN,16.0
29,169,All,Both,40.000000,0.4680,0.4890,0.2980,0.1060,0.0210,NaN,...,NaN,22.00,24.0,0.447,1.000,NaN,0.021,0.043,NaN,16.0
30,169,All,Both,59.000000,0.6250,0.7500,0.3750,0.5000,0.1250,NaN,...,NaN,19.00,29.0,1.000,1.000,NaN,0.250,0.250,NaN,23.0
31,170,All,Both,41.770000,0.5017,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,170,All,Both,44.400000,0.5200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,170,All,Both,40.800000,0.5290,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,170,All,Both,41.300000,0.4940,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,170,All,Both,50.500000,0.6920,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,171,All,Both,53.100000,0.8440,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,171,All,Both,50.800000,0.6440,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,172,All,Both,NaN,0.6226,0.9914,0.5690,0.3276,0.5690,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,173,All,Both,48.000000,0.3750,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,175,All,Both,59.500000,0.5140,0.5200,NaN,NaN,0.2420,0.0400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0
41,175,All,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,175,All,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,175,All,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,176,All,Both,NaN,0.6060,NaN,0.5010,0.2520,0.1370,0.0510,...,NaN,NaN,NaN,NaN,NaN,0.018,NaN,0.048,NaN,NaN
45,176,Severe/critical only,Ventilation only,NaN,0.7080,NaN,0.5380,0.2770,0.1920,0.0540,...,NaN,NaN,NaN,NaN,NaN,0.023,NaN,0.119,NaN,NaN
46,176,All,Non-ventilation only,NaN,0.5550,NaN,0.4830,0.2400,0.1100,0.0490,...,NaN,NaN,NaN,NaN,NaN,0.015,NaN,0.018,NaN,NaN
47,177,All,Both,NaN,0.5660,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,181,All,Both,NaN,NaN,NaN,NaN,0.6767,0.1797,0.1958,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,181,All,Both,NaN,NaN,NaN,NaN,0.7940,0.2580,0.2270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,181,All,Both,NaN,NaN,NaN,NaN,0.5490,0.1330,0.1770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,181,All,Both,NaN,NaN,NaN,NaN,0.6960,0.1650,0.1900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,182,All,Both,NaN,0.6030,NaN,0.5660,0.3380,0.1800,0.0540,...,NaN,33.00,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
test.columns

Index(['ID', 'Severity', 'Ventilation', 'Mean Age', '% Male',
       'Any Comorbidity', 'Hypertension', 'Diabetes',
       'Cardiovascular Disease (incl. CAD)', 'Chronic obstructive lung (COPD)',
       'Cancer (Any)', 'Liver Disease (any)', 'Cerebrovascular Disease',
       'Chronic kidney/renal disease', 'Other', 'Fever (temperature ≥37·3°C)',
       'Average temperature (celsius)', 'Max temperature (celsius)',
       'Respiratory rate > 24 breaths per min', 'Cough',
       'Shortness of Breath (dyspnoea)', 'Headache', 'Sputum (/Expectoration)',
       'Myalgia (Muscle Pain)', 'Fatigue', 'Diarrhoea', 'Nausea or Vomiting',
       'Loss of Appetite/Anorexia', 'Disease Severity Asymptomatic',
       'Disease Severity General', 'Disease Severity Severe',
       'Disease Severity Critical', 'White Blood Cell Count (10^9/L) - Median',
       'White Blood Cell Count (10^9/L) - LQ',
       'White Blood Cell Count (10^9/L) - UQ',
       'Lymphocyte Count (10^9/L) - Median', 'Lymphocyte Count (10^9/L) - LQ',
       'Lymphocyte Count (10^9/L) - UQ', 'Platelet Count (10^9/L) - Median',
       'Platelet Count (10^9/L) - LQ', 'Platelet Count (10^9/L) - UQ',
       'Hemoglobin (g/L) - Median', 'Hemoglobin (g/L) - LQ',
       'Hemoglobin (g/L) - UQ', 'Albumin (g/L)',
       'Alanine Aminotransferase (U/L)', 'Aspartate Aminotransferase (U/L)',
       'Antibiotic', 'Antiviral (Any)', 'Heart failure',
       'Acute kidney injury (AKI)', 'Secondary infection/ Bacterial infection',
       'ICU length of stay, days', 'Hospital length of stay, days'],
      dtype='object')

In [58]:
pd.DataFrame(test.isna().sum()/len(test) * 100).sort_values(by = 0).transpose()

,ID,Severity,Ventilation,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,...,Hemoglobin (g/L) - LQ,Hemoglobin (g/L) - UQ,Antibiotic,Acute kidney injury (AKI),Secondary infection/ Bacterial infection,Heart failure,"ICU length of stay, days",Max temperature (celsius),Other,Albumin (g/L)
0,0.0,0.0,13.207547,15.09434,30.188679,32.075472,33.962264,43.396226,50.943396,50.943396,...,83.018868,83.018868,83.018868,83.018868,86.792453,88.679245,92.45283,94.339623,96.226415,100.0

In [59]:
test = test[pd.DataFrame(test.isna().sum()/len(test) * 100).sort_values(by = 0).index[0:13]]

In [60]:
df1 = df1.reindex(columns = ['ID', 'Severity_scaler', '% Male','Fever (temperature ≥37·3°C)',
             'Mean Age','Cardiovascular Disease (incl. CAD)', 'Diabetes', 
             'Diarrhoea','Hypertension', 'Cough',  'Cancer (Any)',
       'Chronic obstructive lung (COPD)','Mortality'])

In [61]:
test = test.drop("Ventilation",axis=1)

In [62]:
(test.isna().sum()/len(test)) * 100

ID                                     0.000000
Severity                               0.000000
% Male                                15.094340
Fever (temperature ≥37·3°C)           30.188679
Mean Age                              32.075472
Cardiovascular Disease (incl. CAD)    33.962264
Diabetes                              43.396226
Diarrhoea                             50.943396
Hypertension                          50.943396
Cough                                 50.943396
Cancer (Any)                          52.830189
Chronic obstructive lung (COPD)       54.716981
dtype: float64

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
lr = LinearRegression()
le = LabelEncoder()
scaler = MinMaxScaler(feature_range=(0,1))

In [63]:
test["Severity_label"]= pd.DataFrame(le.fit_transform(test["Severity"]))
test["Severity_scaler"] = scaler.fit_transform(test[["Severity_label"]])

In [64]:
test

,ID,Severity,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,Cough,Cancer (Any),Chronic obstructive lung (COPD),Severity_label,Severity_scaler
0,155,Mild only,0.3410,0.7300,48.900000,0.0630,0.1190,0.2220,0.1510,0.6110,0.0630,NaN,3,0.6
1,156,Severe/Critical Only,0.7500,NaN,NaN,0.1100,0.1700,0.0900,0.2500,NaN,NaN,0.1100,4,0.8
2,156,Severe/Critical Only,0.7900,NaN,NaN,0.1800,0.2400,0.0300,0.2600,NaN,NaN,0.1500,4,0.8
3,156,Severe/Critical Only,0.6800,NaN,NaN,0.0000,0.0500,0.2100,0.2100,NaN,NaN,0.0500,4,0.8
4,157,All,0.4654,0.8080,52.943333,0.0733,0.0938,0.0736,0.2121,0.5715,0.0366,0.0327,0,0.0
5,157,All,0.2927,0.7439,44.740000,0.0610,0.0610,0.0732,0.1341,0.4756,0.0244,0.0244,0,0.0
6,157,All,0.4938,0.7654,52.680000,0.0370,0.0741,0.0988,0.1728,0.6049,0.0123,0.0494,0,0.0
7,157,All,0.6098,0.9146,61.410000,0.1220,0.1463,0.0488,0.3293,0.6341,0.0732,0.0244,0,0.0
8,158,All,0.5198,1.0000,36.020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
9,158,All,0.5880,1.0000,40.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
10,158,All,0.3750,1.0000,26.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
11,159,All,0.4700,0.8600,49.000000,0.0600,0.1000,0.1200,0.1900,0.6300,NaN,NaN,0,0.0
12,159,Mild only,0.4400,0.8600,45.000000,0.0300,0.0700,0.1100,0.1000,0.5300,NaN,NaN,3,0.6
13,159,Severe/Critical Only,0.6000,0.8000,67.500000,0.2000,0.2500,0.1500,0.6500,0.6500,NaN,NaN,4,0.8
14,160,All,0.5680,0.9280,38.760000,0.1440,NaN,0.4000,NaN,0.8160,0.0080,0.0160,0,0.0
15,160,Severe/Critical Only,0.6400,NaN,49.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.8
16,160,Mild Only,0.5500,NaN,39.470000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0.4
17,160,Severe/Critical Only,1.0000,1.0000,69.000000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,4,0.8
18,160,Severe/Critical Only,1.0000,1.0000,40.000000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,4,0.8
19,160,Severe/Critical Only,0.0000,0.0000,21.000000,0.0000,0.0000,NaN,0.0000,NaN,0.0000,0.0000,4,0.8
20,160,Severe/Critical Only,1.0000,1.0000,67.000000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,4,0.8
21,161,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.2
22,161,Both,0.6200,0.9100,44.000000,0.0800,0.1700,0.2800,0.3400,0.6800,0.0300,0.0700,1,0.2
23,161,Both,0.7300,0.9200,62.000000,0.1400,0.2100,0.2400,0.4800,0.7000,0.0400,0.1000,1,0.2
24,161,Both,0.5500,0.9000,37.000000,0.0400,0.1400,0.3100,0.2400,0.6600,0.0100,0.0400,1,0.2
25,162,All,0.4740,NaN,45.300000,0.0420,0.0630,0.2000,0.1650,NaN,0.0530,0.0530,0,0.0
26,162,All,0.4660,NaN,48.000000,0.0520,0.0520,0.2420,0.1720,NaN,0.0690,0.0170,0,0.0
27,162,All,0.4860,NaN,41.100000,0.0270,0.0810,NaN,0.1620,NaN,0.0270,0.1080,0,0.0
28,169,All,0.4900,0.8550,45.000000,0.0360,0.1640,0.3270,0.3090,0.6180,0.0360,NaN,0,0.0
29,169,All,0.4680,0.8300,40.000000,0.0210,0.1060,0.2980,0.2980,0.5530,0.0430,NaN,0,0.0
30,169,All,0.6250,1.0000,59.000000,0.1250,0.5000,0.5000,0.3750,1.0000,0.0000,NaN,0,0.0
31,170,All,0.5017,0.4549,41.770000,NaN,NaN,NaN,NaN,0.3065,NaN,NaN,0,0.0
32,170,All,0.5200,0.4210,44.400000,NaN,NaN,NaN,NaN,0.2550,NaN,NaN,0,0.0
33,170,All,0.5290,0.1950,40.800000,NaN,NaN,NaN,NaN,0.3680,NaN,NaN,0,0.0
34,170,All,0.4940,0.4880,41.300000,NaN,NaN,NaN,NaN,0.3110,NaN,NaN,0,0.0
35,170,All,0.6920,0.0000,50.500000,NaN,NaN,NaN,NaN,0.2310,NaN,NaN,0,0.0
36,171,All,0.8440,0.0100,53.100000,NaN,NaN,0.0140,NaN,0.0750,NaN,NaN,0,0.0
37,171,All,0.6440,0.0120,50.800000,NaN,NaN,0.0120,NaN,0.0840,NaN,NaN,0,0.0
38,172,All,0.6226,0.7119,NaN,0.5690,0.3276,0.0593,0.5690,0.5508,0.0517,NaN,0,0.0
39,173,All,0.3750,NaN,48.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
40,175,All,0.5140,NaN,59.500000,0.2420,NaN,NaN,NaN,NaN,NaN,0.0400,0,0.0
41,175,All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
42,175,All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
43,175,All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
44,176,All,0.6060,0.2550,NaN,0.1370,0.2520,0.2370,0.5010,0.7940,0.0590,0.0510,0,0.0
45,176,Severe/critical only,0.7080,0.3460,NaN,0.1920,0.2770,0.2080,0.5380,0.8310,0.0770,0.0540,5,1.0
46,176,All,0.5550,0.2100,NaN,0.1100,0.2400,0.2510,0.4830,0.7760,0.0490,0.0490,0,0.0
47,177,All,0.5660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0
48,181,All,NaN,0.4231,NaN,0.1797,0.6767,NaN,NaN,NaN,0.1604,0.1958,0,0.0
49,181,All,NaN,0.4300,NaN,0.2580,0.7940,NaN,NaN,NaN,0.1800,0.2270,0,0.0
50,181,All,NaN,0.4690,NaN,0.1330,0.5490,NaN,NaN,NaN,0.1300,0.1770,0,0.0
51,181,All,NaN,0.3860,NaN,0.1650,0.6960,NaN,NaN,NaN,0.1700,0.1900,0,0.0
52,182,All,0.6030,NaN,NaN,0.1800,0.3380,NaN,0.5660,NaN,0.0600,0.0540,0,0.0

In [66]:
test = test.reindex(columns = ['ID', 'Severity', 'Severity_label', 'Severity_scaler','% Male', 'Fever (temperature ≥37·3°C)', 'Mean Age',
       'Cardiovascular Disease (incl. CAD)', 'Diabetes', 'Diarrhoea',
       'Hypertension', 'Cough', 'Cancer (Any)',
       'Chronic obstructive lung (COPD)'])

In [67]:
test["% Male"].fillna(test["% Male"].median(),inplace = True)
test[ 'Fever (temperature ≥37·3°C)'].fillna(test[ 'Fever (temperature ≥37·3°C)'].median(),inplace = True)

In [68]:
test1 = test.drop(columns=['Severity', 'Severity_label'],axis = 1)

In [69]:
NC1 = test1.columns[4:]

In [70]:
new_values1 = []
for i in range(len(NC1)):
    lr.fit(test1[test1[NC1[i]].notnull()].iloc[:,[0,1,2,3,4+i]].iloc[:,0:4],
       test1[test1[NC1[i]].notnull()].iloc[:,[0,1,2,3,4+i]][[NC1[i]]])
    new_values1.append(lr.predict(test1[test1[NC1[i]].isnull()].iloc[:,[0,1,2,3,4]].iloc[:,0:4]))

In [71]:
new_values1[1]

array([[ 0.08679133],
       [ 0.129546  ],
       [-0.00398397],
       [ 0.23096811],
       [ 0.13968042],
       [ 0.12961612],
       [ 0.1044661 ],
       [ 0.11458313],
       [ 0.11119019],
       [ 0.10096223],
       [ 0.20557938],
       [ 0.30550263],
       [ 0.18020233],
       [ 0.05015433],
       [ 0.17146552],
       [ 0.17146552],
       [ 0.17146552],
       [ 0.18683039]])

In [72]:
notnull1 = []
isnull1 = []
for  i in range(len(NC1)):
    notnull1.append(test1[test1[NC1[i]].notnull()].iloc[:,[0,1,2,3,4+i]])
    isnull1.append(test1[test1[NC1[i]].isnull()].iloc[:,[0,1,2,3,4+i]])
    notnull1[i].reset_index(drop=True,inplace = True)
    isnull1[i].reset_index(drop=True,inplace = True)    
    isnull1[i][NC1[i]]  = pd.DataFrame(new_values1[i])[0] 
    test1.iloc[:,4+i] = pd.concat([notnull1[i],isnull1[i]],ignore_index=True).iloc[:,-1]

In [73]:
test1.isna().sum()

ID                                    0
Severity_scaler                       0
% Male                                0
Fever (temperature ≥37·3°C)           0
Mean Age                              0
Cardiovascular Disease (incl. CAD)    0
Diabetes                              0
Diarrhoea                             0
Hypertension                          0
Cough                                 0
Cancer (Any)                          0
Chronic obstructive lung (COPD)       0
dtype: int64

In [74]:
test1.head()

,ID,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,Cough,Cancer (Any),Chronic obstructive lung (COPD)
0,155,0.6,0.3410,0.7300,48.900000,0.0630,0.1190,0.2220,0.1510,0.6110,0.0630,0.1100
1,156,0.8,0.7500,0.7654,52.943333,0.1100,0.1700,0.0900,0.2500,0.5715,0.0366,0.1500
2,156,0.8,0.7900,0.7654,44.740000,0.1800,0.2400,0.0300,0.2600,0.4756,0.0244,0.0500
3,156,0.8,0.6800,0.7654,52.680000,0.0000,0.0500,0.2100,0.2100,0.6049,0.0123,0.0327
4,157,0.0,0.4654,0.8080,61.410000,0.0733,0.0938,0.0736,0.2121,0.6341,0.0732,0.0244

In [75]:
df1

,ID,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,Cough,Cancer (Any),Chronic obstructive lung (COPD),Mortality
0,1,0.000000,0.6230,0.940000,49.500000,0.080000,0.190000,0.047100,0.300000,0.790000,0.016800,0.030000,0.28
1,1,0.857143,0.7037,0.944400,44.900000,0.240700,0.314800,0.037000,0.481500,0.722200,0.000000,0.074100,1.00
2,1,0.000000,0.5912,0.941600,48.800000,0.014600,0.138700,0.051100,0.233600,0.817500,0.070000,0.014600,0.00
3,2,0.000000,0.6030,0.915000,52.300000,0.100000,0.116000,0.020600,0.150000,0.590000,0.030000,0.110000,0.16
4,2,0.000000,0.6160,0.899000,49.500000,0.200000,0.101000,0.042000,0.130000,0.000000,0.051000,0.070000,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,0.857143,0.6630,0.601472,49.490090,0.349657,0.259824,0.200831,0.268238,0.663329,0.084291,0.078594,0.56
471,198,0.000000,0.6600,0.637644,50.128415,0.148943,0.305341,0.249024,0.336715,0.623641,0.084849,0.091873,0.58
472,199,0.857143,0.5900,0.636763,55.758071,0.124150,0.171766,0.250866,0.490725,0.657676,0.180093,0.124468,1.00
473,199,0.857143,0.5600,0.624952,61.961463,0.271933,0.245874,0.234978,0.432168,0.672993,0.075274,0.041530,0.00
474,199,0.857143,0.6500,0.569376,55.020322,0.097850,0.134597,0.239986,0.178454,0.680539,0.065910,0.045788,0.00

In [76]:
df1

,ID,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,Cough,Cancer (Any),Chronic obstructive lung (COPD),Mortality
0,1,0.000000,0.6230,0.940000,49.500000,0.080000,0.190000,0.047100,0.300000,0.790000,0.016800,0.030000,0.28
1,1,0.857143,0.7037,0.944400,44.900000,0.240700,0.314800,0.037000,0.481500,0.722200,0.000000,0.074100,1.00
2,1,0.000000,0.5912,0.941600,48.800000,0.014600,0.138700,0.051100,0.233600,0.817500,0.070000,0.014600,0.00
3,2,0.000000,0.6030,0.915000,52.300000,0.100000,0.116000,0.020600,0.150000,0.590000,0.030000,0.110000,0.16
4,2,0.000000,0.6160,0.899000,49.500000,0.200000,0.101000,0.042000,0.130000,0.000000,0.051000,0.070000,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,197,0.857143,0.6630,0.601472,49.490090,0.349657,0.259824,0.200831,0.268238,0.663329,0.084291,0.078594,0.56
471,198,0.000000,0.6600,0.637644,50.128415,0.148943,0.305341,0.249024,0.336715,0.623641,0.084849,0.091873,0.58
472,199,0.857143,0.5900,0.636763,55.758071,0.124150,0.171766,0.250866,0.490725,0.657676,0.180093,0.124468,1.00
473,199,0.857143,0.5600,0.624952,61.961463,0.271933,0.245874,0.234978,0.432168,0.672993,0.075274,0.041530,0.00
474,199,0.857143,0.6500,0.569376,55.020322,0.097850,0.134597,0.239986,0.178454,0.680539,0.065910,0.045788,0.00

In [77]:
test1

,ID,Severity_scaler,% Male,Fever (temperature ≥37·3°C),Mean Age,Cardiovascular Disease (incl. CAD),Diabetes,Diarrhoea,Hypertension,Cough,Cancer (Any),Chronic obstructive lung (COPD)
0,155,0.6,0.3410,0.7300,48.900000,0.063000,0.119000,0.222000,0.151000,0.611000,0.063000,0.110000
1,156,0.8,0.7500,0.7654,52.943333,0.110000,0.170000,0.090000,0.250000,0.571500,0.036600,0.150000
2,156,0.8,0.7900,0.7654,44.740000,0.180000,0.240000,0.030000,0.260000,0.475600,0.024400,0.050000
3,156,0.8,0.6800,0.7654,52.680000,0.000000,0.050000,0.210000,0.210000,0.604900,0.012300,0.032700
4,157,0.0,0.4654,0.8080,61.410000,0.073300,0.093800,0.073600,0.212100,0.634100,0.073200,0.024400
5,157,0.0,0.2927,0.7439,36.020000,0.061000,0.061000,0.073200,0.134100,0.630000,0.008000,0.049400
6,157,0.0,0.4938,0.7654,40.500000,0.037000,0.074100,0.098800,0.172800,0.530000,0.000000,0.024400
7,157,0.0,0.6098,0.9146,26.500000,0.122000,0.146300,0.048800,0.329300,0.650000,0.030000,0.016000
8,158,0.0,0.5198,1.0000,49.000000,0.060000,0.100000,0.120000,0.190000,0.816000,0.040000,0.000000
9,158,0.0,0.5880,1.0000,45.000000,0.030000,0.070000,0.110000,0.100000,0.680000,0.010000,0.070000
10,158,0.0,0.3750,1.0000,67.500000,0.200000,0.250000,0.150000,0.650000,0.700000,0.053000,0.100000
11,159,0.0,0.4700,0.8600,38.760000,0.144000,0.000000,0.400000,0.000000,0.660000,0.069000,0.040000
12,159,0.6,0.4400,0.8600,49.400000,1.000000,0.170000,0.280000,0.340000,0.618000,0.027000,0.053000
13,159,0.8,0.6000,0.8000,39.470000,0.000000,0.210000,0.240000,0.480000,0.553000,0.036000,0.017000
14,160,0.0,0.5680,0.9280,69.000000,0.000000,0.140000,0.310000,0.240000,1.000000,0.043000,0.108000
15,160,0.8,0.6400,0.7654,40.000000,1.000000,0.063000,0.200000,0.165000,0.306500,0.000000,0.040000
16,160,0.4,0.5500,0.7654,21.000000,0.080000,0.052000,0.242000,0.172000,0.255000,0.051700,0.051000
17,160,0.8,1.0000,1.0000,67.000000,0.140000,0.081000,0.327000,0.162000,0.368000,0.059000,0.054000
18,160,0.8,1.0000,1.0000,44.000000,0.040000,0.164000,0.298000,0.309000,0.311000,0.077000,0.049000
19,160,0.8,0.0000,0.0000,62.000000,0.042000,0.106000,0.500000,0.298000,0.231000,0.049000,0.195800
20,160,0.8,1.0000,1.0000,37.000000,0.052000,0.500000,0.014000,0.375000,0.075000,0.160400,0.227000
21,161,0.2,0.5550,0.7654,45.300000,0.027000,0.327600,0.012000,0.569000,0.084000,0.180000,0.177000
22,161,0.2,0.6200,0.9100,48.000000,0.036000,0.252000,0.059300,0.501000,0.550800,0.130000,0.190000
23,161,0.2,0.7300,0.9200,41.100000,0.021000,0.277000,0.237000,0.538000,0.794000,0.170000,0.054000
24,161,0.2,0.5500,0.9000,45.000000,0.125000,0.240000,0.208000,0.483000,0.831000,0.060000,0.010401
25,162,0.0,0.4740,0.7654,40.000000,0.569000,0.676700,0.251000,0.566000,0.776000,0.010896,0.041306
26,162,0.0,0.4660,0.7654,59.000000,0.242000,0.794000,0.222896,0.218168,0.648339,0.011715,0.052307
27,162,0.0,0.4860,0.7654,41.770000,0.137000,0.549000,0.216483,0.252975,0.652230,0.009463,0.017950
28,169,0.0,0.4900,0.8550,44.400000,0.192000,0.696000,0.236512,0.144267,0.641531,0.020736,0.041588
29,169,0.0,0.4680,0.8300,40.800000,0.110000,0.338000,0.171724,0.267991,0.654879,0.022133,0.030069
30,169,0.0,0.6250,1.0000,41.300000,0.179700,0.101025,0.169783,0.333161,0.661513,0.017772,0.056221
31,170,0.0,0.5017,0.4549,50.500000,0.258000,0.116980,0.227398,0.271877,0.640795,0.027811,0.066472
32,170,0.0,0.5200,0.4210,53.100000,0.133000,0.067149,0.227398,0.520181,0.702606,0.014344,0.056409
33,170,0.0,0.5290,0.1950,50.800000,0.165000,0.144671,-0.060179,0.520181,0.614386,0.015524,0.114490
34,170,0.0,0.4940,0.4880,48.000000,0.180000,0.175495,0.227398,0.520181,0.893001,0.020592,0.114490
35,170,0.0,0.6920,0.0000,59.500000,0.086791,0.143722,0.178535,0.279870,0.893001,0.027318,0.114490
36,171,0.0,0.8440,0.0100,53.040740,0.129546,0.270473,0.194245,0.358688,0.133419,0.019405,0.061759
37,171,0.0,0.6440,0.0120,54.217838,-0.003984,0.270473,0.189672,0.367553,0.893001,0.019405,0.068200
38,172,0.0,0.6226,0.7119,50.980819,0.230968,0.270473,0.175014,0.368980,0.591381,0.019405,0.065722
39,173,0.0,0.3750,0.7654,47.082676,0.139680,0.157369,0.087925,0.355222,0.560011,0.034692,0.083764
40,175,0.0,0.5140,0.7654,50.648648,0.129616,0.285827,0.203027,0.449438,0.559233,0.076095,0.089545
41,175,0.0,0.5550,0.7654,49.507404,0.104466,0.288554,-0.001816,0.540270,0.561178,0.077706,0.093949
42,175,0.0,0.5550,0.7654,49.507404,0.114583,0.280297,0.363347,0.438225,0.729039,0.086135,0.105083
43,175,0.0,0.5550,0.7654,49.507404,0.111190,0.285544,0.379125,0.337723,0.775042,0.074730,0.086885
44,176,0.0,0.6060,0.2550,48.916914,0.100962,0.309489,0.375269,0.434897,0.779030,0.096585,0.139729
45,176,1.0,0.7080,0.3460,54.381485,0.205579,0.363344,0.375269,0.455822,0.779030,0.102320,0.166136
46,176,0.0,0.5550,0.2100,47.213876,0.305503,0.316646,0.375269,0.455822,0.779030,0.098152,0.133790
47,177,0.0,0.5660,0.7654,50.236182,0.180202,0.323931,0.403083,0.455822,0.812583,0.071135,0.102671
48,181,0.0,0.5550,0.4231,49.184274,0.050154,0.392122,0.331189,0.487669,0.649768,0.079955,0.062758
49,181,0.0,0.5550,0.4300,49.215284,0.171466,0.401714,0.333822,0.529724,0.654338,0.080795,0.096426
50,181,0.0,0.5550,0.4690,49.390557,0.171466,0.401714,0.348705,0.529821,0.680168,0.080795,0.096426
51,181,0.0,0.5550,0.3860,49.017540,0.171466,0.401714,0.317031,0.530367,0.625196,0.080795,0.096426
52,182,0.0,0.6030,0.7654,52.337686,0.186830,0.439959,0.471724,0.529204,0.897389,0.086994,0.102835

In [78]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [79]:
lr.fit(df1.drop("Mortality",axis= 1),df["Mortality"])

LinearRegression()

In [80]:
pd.DataFrame(lr.predict(test1))[0]

0     0.263912
1     0.292968
2     0.281190
3     0.278391
4     0.042556
5     0.103479
6     0.082450
7     0.118975
8     0.058447
9     0.070904
10    0.064944
11    0.098120
12    0.193822
13    0.335018
14    0.042790
15    0.245484
16    0.262337
17    0.232742
18    0.309565
19    0.348427
20    0.367371
21    0.215192
22    0.192396
23    0.194371
24    0.148482
25    0.075959
26    0.019639
27    0.071334
28    0.055514
29    0.085403
30    0.087620
31    0.071084
32    0.087307
33    0.092159
34    0.107666
35    0.062642
36    0.064868
37    0.076205
38    0.063516
39    0.094055
40    0.098315
41    0.100824
42    0.111160
43    0.097641
44    0.125689
45    0.382315
46    0.120105
47    0.102452
48    0.109086
49    0.111689
50    0.111323
51    0.112160
52    0.103257
Name: 0, dtype: float64

In [51]:
lr.predict(test1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 20 is different from 12)

In [81]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [82]:
dt = DecisionTreeRegressor()
rf = RandomForestRegressor(n_estimators = 150)

In [83]:
dt.fit(df1.drop("Mortality",axis= 1),df["Mortality"])
rf.fit(df1.drop("Mortality",axis= 1),df["Mortality"])

RandomForestRegressor(n_estimators=150)

In [84]:
dt.predict(test1)

array([0.2 , 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.23,
       0.14, 0.2 , 0.45, 0.  , 0.4 , 0.66, 0.36, 0.29, 0.15, 0.7 , 0.02,
       0.02, 0.2 , 0.2 , 0.23, 0.23, 0.23, 0.23, 0.23, 0.  , 0.  , 0.  ,
       0.01, 0.  , 0.  , 0.  , 0.  , 0.23, 0.  , 0.23, 0.23, 0.23, 0.23,
       0.14, 0.56, 0.09, 0.23, 0.14, 0.14, 0.14, 0.14, 0.23])

In [85]:
mortality_dt = pd.DataFrame(columns=["ID","Mortality"])
mortality_dt["ID"] =test1.iloc[:,0]
mortality_dt["Mortality"] =pd.DataFrame(dt.predict(test1))[0]
# mortality_dt.to_csv("D:\\Skillenza_Bootcamp\\ML Level2\\Problem2\\mortality_predict_dt1.csv")

In [86]:
rf.predict(test1)

array([0.14493333, 0.437     , 0.24873333, 0.15      , 0.21766667,
       0.18033333, 0.17213333, 0.1942    , 0.22653333, 0.2314    ,
       0.26706667, 0.26246667, 0.175     , 0.56733333, 0.2788    ,
       0.55213333, 0.1384    , 0.27146667, 0.29993333, 0.39586667,
       0.659     , 0.20626667, 0.2136    , 0.24073333, 0.2138    ,
       0.18506667, 0.22486667, 0.17506667, 0.1722    , 0.19153333,
       0.21413333, 0.17393333, 0.25753333, 0.20206667, 0.2266    ,
       0.2736    , 0.19946667, 0.26613333, 0.1408    , 0.1462    ,
       0.1546    , 0.13653333, 0.19753333, 0.18806667, 0.19866667,
       0.58833333, 0.19473333, 0.19926667, 0.14333333, 0.19873333,
       0.20193333, 0.1848    , 0.205     ])

In [68]:
# mortality_rf = pd.DataFrame(columns=["ID","Mortality"])
# mortality_rf["ID"] =test1.iloc[:,0]
# mortality_rf["Mortality"] =pd.DataFrame(rf.predict(test1))[0]
# mortality_rf.to_csv("D:\\Skillenza_Bootcamp\\ML Level2\\Problem2\\mortality_predict_rf1.csv")